### ISSUE TITLE
Issue 1 remains in posted version. Work around shown in issue

### ISSUE THREAD

**Issue by ghost** [minisllc/metatwin#5]
Just leaving a note that Issue 1 remains in current posted version of PS1 file. 
Issue fixed by changing the following lines to full path. 
replace the following ".\" with the current directory of 'metatwin' on lines 94-96,114, and 119-122. This could be accomplished by adding a method to get the CWD of code at 119-122,94-96 and 114 and replacing the ".\" string with that variable. variable would have to come before line 94. 

After modifications script works as desired. 

Example workaround below:
**93-95**

```
$resourceHackerBin = "C:\Users\User\Documents\metatwin-master\metatwin-master\src\resource_hacker\ResourceHacker.exe"
$resourceHacker_base_script = "C:\Users\User\Documents\metatwin-master\metatwin-master\src\rh_base_script.txt"
$sigthiefBin       = "C:\Users\User\Documents\metatwin-master\metatwin-master\src\SigThief-master\dist\sigthief.exe"
```

**112-121:**
Could change $log_file_base in code. But I did not.
```
$timestamp = Get-Date -f yyyyMMdd_HHmmss
$log_file_base = (".\" + $timestamp + "\" + $timestamp)
$source_binary_filename = Split-Path $Source -Leaf -Resolve
$source_binary_filepath = $Source
$target_binary_filename = Split-Path $Target -Leaf -Resolve
$target_binary_filepath = $Target
$source_resource = ("C:\Users\User\Documents\metatwin-master\metatwin-master\" + $timestamp + "\" + $timestamp + "_" + $source_binary_filename + ".res")
$target_saveas = ("C:\Users\User\Documents\metatwin-master\metatwin-master\" + $timestamp + "\" + $timestamp + "_" + $target_binary_filename)
$target_saveas_signed = ("C:\Users\User\Documents\metatwin-master\metatwin-master\" + $timestamp + "\" + $timestamp + "_signed_" + $target_binary_filename)
$resourcehacker_script = ("C:\Users\User\Documents\metatwin-master\metatwin-master\" + $timestamp + "\" + $timestamp + "_rh_script.txt")
```

Example of proposed fix in code would be (wont work for $Source and $Target):
`$log_file_base = ($CWDvariable +"\"+ $timestamp + "\" + $timestamp)`

**Comment by ghost** [comment]
better solution found. via replacing all ".\" with use of $PSScriptRoot

**Comment by Verity-Freedom** [comment]
What did you mean by "replacing all "."? Wtf? I did it and I only getting "missing dependency". Why you didn't tell in which lines it was supposed to be done?
